### ISSUE TITLE
[volume-widget] the icon would not update at volume level change via keyboard

### ISSUE THREAD

**Issue by pemakhov** [streetturtle/awesome-wm-widgets#118]
Everything works perfectly when I change the volume level by scrolling with the hovering cursor. But when I change the volume level using keyboard shortcuts, the icon would not update.

**Comment by pemakhov** [comment]
There was another problem. I couldn't turn off notification even though `display_notification = false` is a default option. So I wrote `display_notification = false` in volume.lua file before the block of code beginning with `if display_notification then`
First, it actually disabled displaying the notification. But moreover, it fixed my initial problem.

**Comment by streetturtle** [comment]
Thank you for raising an issue! There actually was a problem with display_notification parameter. The default value was a string (`''false`) instead of a boolean (`false`), so I guess it broke some part of the logic. And another small thing is this parameter is called `display_notification` internally in widget's code, but `notification` in the constructor in rc.lua which seems a bit misleading.  
Not these two issues are fixed.

**Comment by d9d6ka** [comment]
> Everything works perfectly when I change the volume level by scrolling with the hovering cursor. But when I change the volume level using keyboard shortcuts, the icon would not update.

I'm terribly sorry for (maybe) necroposting, but the initial problem still occurs for me. The icon in tray updates only by mousebutton actions, not by keyboard shortcuts.
Actually I had to detach icon to the separate local widget (like in your bat widget, which updates perfectly every 15 secs), otherwise it didn't updated even by mousebuttons.
